name: functionalTest

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  functionalTest:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.java-version

      - run: ./gradlew :plugin:functionalTest

      - name: Publish functional test results (Linux)
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2
        if: ${{ !cancelled() && runner.os == 'Linux' }}
        with:
          check_name: functionalTest results (Linux)
          comment_mode: off
          files: plugin/build/test-results/functionalTest/TEST-*.xml

      - name: Publish functional test results (Windows)
        uses: EnricoMi/publish-unit-test-result-action/windows@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2
        if: ${{ !cancelled() && runner.os == 'Windows' }}
        with:
          check_name: functionalTest results (Windows)
          comment_mode: off
          files: plugin/build/test-results/functionalTest/TEST-*.xml
